version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 30
    directory: "/"
    schedule:
      interval: "weekly"

    cooldown:
      default-days: 1
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 30
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
